// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC44AQuIG07qL_UH5-KbscU6AZm8WRO2pQ',
    appId: '1:893088102883:web:4a78456db075ecf69ac8d6',
    messagingSenderId: '893088102883',
    projectId: 'e-commerce1-94dae',
    authDomain: 'e-commerce1-94dae.firebaseapp.com',
    storageBucket: 'e-commerce1-94dae.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvV3Y3xWaw_c6LzRFXlHqkpWgNWcTo2ps',
    appId: '1:893088102883:android:d37f2329b686371a9ac8d6',
    messagingSenderId: '893088102883',
    projectId: 'e-commerce1-94dae',
    storageBucket: 'e-commerce1-94dae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdWl2KsiPutn-gvYn8dlj--q9Fm6-gjKc',
    appId: '1:893088102883:ios:4bfbe21da3183fe19ac8d6',
    messagingSenderId: '893088102883',
    projectId: 'e-commerce1-94dae',
    storageBucket: 'e-commerce1-94dae.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdWl2KsiPutn-gvYn8dlj--q9Fm6-gjKc',
    appId: '1:893088102883:ios:4bfbe21da3183fe19ac8d6',
    messagingSenderId: '893088102883',
    projectId: 'e-commerce1-94dae',
    storageBucket: 'e-commerce1-94dae.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC44AQuIG07qL_UH5-KbscU6AZm8WRO2pQ',
    appId: '1:893088102883:web:1adcfc24fb7a7ea49ac8d6',
    messagingSenderId: '893088102883',
    projectId: 'e-commerce1-94dae',
    authDomain: 'e-commerce1-94dae.firebaseapp.com',
    storageBucket: 'e-commerce1-94dae.firebasestorage.app',
  );
}
